# IdleRestart Configuration

# Number of minutes to wait before restarting the server when idle
idle-minutes: 10

# Number of players below which the server is considered idle
number-of-players: 0

# Whether to broadcast a message with a sound when a restart is scheduled
broadcast-restart: true

# Sound to play when a restart is broadcasted
restart-sound: ENTITY_PLAYER_LEVELUP

# Delay in minutes to restart when a player joins
join-delay-minutes: 5

idle-prefix: "&8&l[&6&lIR🕙&8&l]&r"

# Scheduled Restarts
# Enable or disable scheduled restarts
scheduled-restarts:
  enabled: false
  # A list of times in HH:mm format (24-hour clock) to restart the server
  times:
    - "04:00"
    - "16:00"
  # The timezone to use for scheduled restarts.
  # A list of valid timezones can be found here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timezone: "UTC"

# Discord Webhook
# Enable or disable Discord webhook notifications
discord:
  enabled: false
  # The webhook URL from Discord
  webhook-url: ""
  # The name of the server to display in the notification
  server-name: "My Server"
